url: https://vasiliy-dudin.com
title: Tatiana Fokina - web developer
description: Tatiana Fokina is a web developer. Information about her, her skills, pet-projects and activities.
lang: ru
ogImageLink: https://vasiliy-dudin.com/assets/og-image.jpg